import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { EXAMPLES } from "@/data/examples";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="absolute grid h-screen w-screen grid-cols-[400px_repeat(3,_minmax(0,_1fr))] overflow-hidden">
        <div className="col-span-1">
          <Sidebar examples={EXAMPLES} />
        </div>
        <div className="col-span-3">{children}</div>
      </body>
    </html>
  );
}
